spring.application.name=bookstore4

#接続設定
spring.datasource.url=jdbc:h2:file:./data/bookstore
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#H2コンソール
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA
spring.jpa.hibernate.ddl-auto=update

#初期データ
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true